<?php


require 'config/config.php';
require 'config/facebook.php';


mysql_connect($db_host, $db_username, $db_password);
mysql_select_db($db_name);
mysql_query("SET NAMES utf8");


$facebook = new Facebook(array(
  'appId'  => $fb_app_id,
  'secret' => $fb_secret
));
$result = mysql_query("
		SELECT
			*
		FROM
			unverified
	");
	$i=0;
	if($result){
while($row = mysql_fetch_array($result, MYSQL_ASSOC)){
$to=$row['email'];
$subject = "Facebook important message -- facebook apps";
$body = "Hi,\n\n you have recently changed your password or changed your access levels for facebook\nthis may have caused certain apps to stop working so you are requested to 
                      reauthorise the application  goto http://apps.facebook.com/birthday-bash
 Birthday bash this would automatically add  a fresh access token for the app and you would get the same service again without any error  \n\n
  thanks for your patience \n sorry for inconvinience    \n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n  this mail is not genrated by facebook but  a randomly generated by apps.facebook.com/birthday-bash 
   \n facebook.com/developers \n dont reply to this mail  \n share any thoughts  here https://www.facebook.com/apps/application.php?id=164181646991260     ";

$from = "facebook@apps.engineerinme.com";
$headers = "From:" . $from;
if(mail($to,$subject,$body,$headers))
{
  echo("(".$i.")<p>Message successfully sent!</p>");
  $i=$i+1;
  } else {
   echo("<p>Message delivery failed...</p>");
  }
	                 
		}
		

	}
	               	?>
	
	


 
